### ISSUE TITLE
Chart shows dot for single item in the data array

### ISSUE THREAD

**Issue by jagataess** [Novsochetra/react-native-circular-chart#6]
Whenever I have only a single item in the data array, the chart shows just a dot instead of showing the full circle.

**Comment by Novsochetra** [comment]
@jagataess let me try to reproduce it then. 

thank you

**Comment by jagataess** [comment]
I've already got the solution for this issue. The solution is to replace the `d.to` with `d.to-1` for the `endAngle`.
Like this - 
`const arcParams: ArcParams = {
  coordX: viewBox.getCenterCoord().x,
  coordY: viewBox.getCenterCoord().y,
  radius: radius,
  startAngle: d.from,
  endAngle: d.to-1,
};`
